### ISSUE TITLE
Getting lots of errors.

### ISSUE THREAD

**Issue by Shnxxx** [call-042PE/FuckVanguard#1]
![image](https://user-images.githubusercontent.com/48496678/103882587-0252a380-5117-11eb-820b-6f46e5770430.png)

Any clue why?

**Comment by call-042PE** [comment]
You have to install the interception driver and change the dll path in the interception.py

**Comment by Shnxxx** [comment]
Thank you for your response! I opened `interception.py` and couldn't find the line that is pointing to the `interception.dll` so I could change the path.

**Comment by call-042PE** [comment]
sry you don't need dll just installing the driver should be good
