### ISSUE TITLE
First It was working now it not

### ISSUE THREAD

**Issue by somenormalguy7** [call-042PE/FuckVanguard#10]
Hello
first triggerbot was working but I reinstalled the window for some reason and python too installed all modules but nothing is working other then B-Hop , game setting is also set to fullscreen windowed and color is purple

python version 3.8.8
https://i.imgur.com/kKO3ggb.png 

Am I doing something wrong

**Comment by GMGuimaraes** [comment]
[
![1](https://user-images.githubusercontent.com/62194953/109480576-126d6c00-7a52-11eb-8370-cf920549a0be.PNG)
](url)


The program ran but does nothing in the game, after a while it appears to me.

**Comment by call-042PE** [comment]
dont use aimassist is bad but if you want you have to download interception driver
