### ISSUE TITLE
FuckVanguard.py not closing immediately when opening.

### ISSUE THREAD

**Issue by Sweamm** [call-042PE/FuckVanguard#12]
FuckVanguard.py immediately closes when I open it.
Windows Defender Real-Time Protection is turned off. 
Using Python 3.9.2 with PATH.
This is what u see when opened with ILDE and F5 pressed
![IDLE_F5](https://user-images.githubusercontent.com/72986088/109788455-a0db1c80-7c0f-11eb-920f-4ecb894340bb.png)

**Comment by N3agu** [comment]
That error shows up bcs you don't have the module named 'keyboard'. Open your cmd and type "pip install keyboard", then press enter.
