### ISSUE TITLE
ModuleNotFoundError: No module named 'keyboard'

### ISSUE THREAD

**Issue by circulet** [call-042PE/FuckVanguard#6]
> C:\Users\Circ\Desktop\FuckVanguard-main>py FuckVanguard.py
> Traceback (most recent call last):
> File "FuckVanguard.py", line 3, in <module>
> import keyboard
> ModuleNotFoundError: No module named 'keyboard'
> 
> C:\Users\Circ\Desktop\FuckVanguard-main>pip install keyboard
> Requirement already satisfied: keyboard in c:\users\Circ\appdata\local\programs\python\python39\lib\site-packages (0.13.5)

Not sure what to do to fix as I can't pinpoint the problem. Tried and failed so many times to fix python but desperate for help.

**Comment by somenormalguy7** [comment]
pip install keyboard

**Comment by revaxsy** [comment]
pip install keybnoard

**Comment by call-042PE** [comment]
You have two python installed and when you type "py FuckVanguard.py" it's load on another python try to remove this python
